# import des librairies

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [23]:

# Read dataset to pandas dataframe
dataset = pd.read_csv("jeu2Donne.csv")

In [24]:
#X = data.drop('Class', axis=1)
#y = data['Class']

In [26]:
x_train = train[["nHM","ON1V","X2Av","PCD","piPC09","MLOGP","N-072","B02[C-N]","F04[C-O]","logBCF"]]
y_train = train[["Class"]]
x_test = test[["nHM","ON1V","X2Av","PCD","piPC09","MLOGP","N-072","B02[C-N]","F04[C-O]","logBCF"]]
y_test = test[["Class"]]

In [27]:
# Polynomial Kernel
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(x_train, y_train)

/opt/conda/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVC(degree=8, kernel='poly')

In [29]:
y_pred = svclassifier.predict(x_test)

In [30]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred)) 

[[106   3   6]
 [ 10   5   1]
 [ 43   0  21]]
              precision    recall  f1-score   support

           1       0.67      0.92      0.77       115
           2       0.62      0.31      0.42        16
           3       0.75      0.33      0.46        64

    accuracy                           0.68       195
   macro avg       0.68      0.52      0.55       195
weighted avg       0.69      0.68      0.64       195



In [32]:
#. Gaussian Kernel

from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(x_train, y_train)


/opt/conda/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVC()

In [34]:
y_pred = svclassifier.predict(x_test)

In [35]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[99  0 16]
 [14  0  2]
 [35  0 29]]
              precision    recall  f1-score   support

           1       0.67      0.86      0.75       115
           2       0.00      0.00      0.00        16
           3       0.62      0.45      0.52        64

    accuracy                           0.66       195
   macro avg       0.43      0.44      0.43       195
weighted avg       0.60      0.66      0.62       195



/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [36]:
# Sigmoid Kernel

from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(x_train, y_train)


/opt/conda/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVC(kernel='sigmoid')

In [37]:
y_pred = svclassifier.predict(x_test)

In [38]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[84  0 31]
 [ 6  0 10]
 [42  0 22]]
              precision    recall  f1-score   support

           1       0.64      0.73      0.68       115
           2       0.00      0.00      0.00        16
           3       0.35      0.34      0.35        64

    accuracy                           0.54       195
   macro avg       0.33      0.36      0.34       195
weighted avg       0.49      0.54      0.51       195



/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
